title: Out of context notes
description: This website holds my research and study notes for the project where I mechanistically investigate the out of context meta-learning phenomena that occurs in large language models.
theme: just-the-docs

url: https://firstuserhere.github.io/outofcontextnotes
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  readings:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    readings:
      # Give the collection a name
      name: Readings
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true