title: Out of context notes
description: This website holds my research and study notes for the project where I mechanistically investigate the out of context meta-learning phenomena that occurs in large language models.
theme: just-the-docs

url: https://firstuserhere.github.io/outofcontextnotes
