title: Out of context notes
description: Hello! This is a website to hold my working notes while investigating the meta out-of-context learning phenomena. Here I will be writing notes and musings and general thoughts and my confusions while working my way through this project. You can find the polished posts at the [project website](https://firstuserhere.github.io/metalearning)
theme: just-the-docs

url: https://firstuserhere.github.io/outofcontextnotes
color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  abstract:
    title: Abstract
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  abstract-cont:
    color: green

collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  readings:
    permalink: "/:collection/:path/"
    output: true
  
  confusions:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    readings:
      # Give the collection a name
      name: Readings
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
    confusions:
      name: confusions